/* eslint-disable react/prop-types */
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { Badge, Card, EmptyState, ErrorState, SectionHeading, Skeleton, Toggle } from "../components/ui";
import { useApi } from "../hooks/useApi";
import { timeAgo } from "../lib/format";

/*
  Where every number on this platform comes from.

  This screen exists because the console mixes three very different kinds of input and draws
  them identically. A corridor's incident count is real people reporting real obstructions.
  Its rainfall figure is a value someone typed into a CSV that has not changed since the
  repository was cloned. Its landslide history is invented. On a dashboard all three are a
  number in the same weight of the same font, and the person deciding whether to move a
  convoy has no way to tell them apart.

  So the honest thing is not a disclaimer at the bottom of an About page. It is a screen that
  names each input, says plainly what it is, and shows what a real deployment would put in
  its place — served from the backend module that does the loading, so the claim here cannot
  quietly drift away from the code.

  Trust is the sort order and the filter, because it is the only property that changes what
  an operator should do with the number.
*/

const TRUST_META = {
  live: {
    tone: "success",
    label: "Live",
    line: "Real data, arriving now.",
  },
  sample: {
    tone: "warning",
    label: "Sample",
    line: "Real-world shape, illustrative values. A stand-in for a feed that is not wired in.",
  },
  synthetic: {
    tone: "danger",
    label: "Synthetic",
    line: "Generated by us. Carries no real-world information.",
  },
  derived: {
    tone: "info",
    label: "Derived",
    line: "Computed from the inputs above. Inherits their trust.",
  },
};

const TRUST_ORDER = ["live", "sample", "synthetic", "derived"];

/** The database figures, when the manifest could reach the database. Rendered as a sentence
 *  rather than a stat row: the useful fact is the split between clients, not the total. */
const LiveStats = ({ stats }) => {
  if (!stats || stats.total === null || stats.total === undefined) return null;
  const bySource = stats.by_source || {};
  const named = { app: "the field app", web: "the web console", api: "direct API calls" };
  const parts = Object.entries(bySource)
    .filter(([, count]) => count > 0)
    .map(([key, count]) => `${count} from ${named[key] || key}`);

  return (
    <div className="mt-3 rounded-lg border border-white/10 p-3" style={{ backgroundColor: "var(--surface-sunken)" }}>
      <p className="label-micro mb-1.5">In the database right now</p>
      <p className="text-sm text-ink">
        {stats.total} report{stats.total === 1 ? "" : "s"}
        {parts.length ? ` — ${parts.join(", ")}` : ""}.
      </p>
      <p className="text-[11px] text-ink-muted mt-1">
        {stats.database ? `Stored in ${stats.database}. ` : ""}
        {stats.latest_reported_at ? `Most recent ${timeAgo(stats.latest_reported_at)}.` : "None filed yet."}
      </p>
    </div>
  );
};

/** Live-feed state, when the source has one.
 *
 *  Rainfall is the one input whose trust level changes at runtime — live while Open-Meteo
 *  answers, the shipped snapshot when it does not. Showing the age of the last fetch is what
 *  lets a reader tell those apart at a glance instead of taking the badge on faith. */
const FeedStatus = ({ weather }) => {
  if (!weather) return null;
  const live = weather.state === "live";
  return (
    <div
      className="mt-2 rounded-lg border border-white/10 p-3"
      style={{ backgroundColor: "var(--surface-sunken)" }}
    >
      <p className="label-micro mb-1.5">Live feed</p>
      <p className="text-sm text-ink">
        {live
          ? `${weather.corridors} corridors, fetched ${timeAgo(weather.fetched_at)}`
          : "Not answering — showing the shipped snapshot instead"}
      </p>
      <p className="text-[11px] text-ink-muted mt-1">{weather.source}</p>
      {weather.error && (
        <p className="text-[11px] text-ink-muted mt-1">Last error: {weather.error}</p>
      )}
    </div>
  );
};

/** A shipped file: which one, and when it last changed. The date is the point — it is what
 *  shows a "current conditions" snapshot to be months old. */
const FileMeta = ({ storage }) => {
  if (!storage || typeof storage !== "object") {
    return storage ? <p className="text-xs text-ink-secondary">{storage}</p> : null;
  }
  const live = storage.weather?.state === "live";
  const ranges = [
    ["Observed rainfall (24h)", storage.rainfall_mm_24h_range, "mm"],
    ["Forecast rainfall (48h)", storage.forecast_rainfall_mm_48h_range, "mm"],
  ].filter(([, range]) => Array.isArray(range));

  return (
    <div className="text-xs text-ink-secondary space-y-1">
      {storage.file && (
        <p>
          <code className="text-[11px] text-ink-muted break-all">{storage.file}</code>
        </p>
      )}
      {storage.last_modified && (
        <p className="text-ink-muted">
          Last changed {timeAgo(storage.last_modified)}
          {storage.segments_covered ? ` · ${storage.segments_covered} corridors` : ""}
        </p>
      )}
      {ranges.map(([label, [lo, hi], unit]) => (
        <p key={label} className="text-ink-muted">
          {label}: {lo}–{hi} {unit} across the network
          {live ? ", right now." : ", frozen."}
        </p>
      ))}
    </div>
  );
};

const SourceCard = ({ source }) => {
  const meta = TRUST_META[source.trust] || TRUST_META.derived;
  const warns = source.trust === "sample" || source.trust === "synthetic";
  const [open, setOpen] = useState(false);

  return (
    <Card className="!p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <h3 className="text-base font-semibold text-ink">{source.name}</h3>
          <p className="text-sm text-ink-secondary mt-1">{source.summary}</p>
        </div>
        <Badge tone={meta.tone}>{meta.label}</Badge>
      </div>

      <p className="text-xs text-ink-secondary mt-3 leading-relaxed">{source.origin}</p>

      {/* Amber is reserved for a caveat that is a warning about the data's trustworthiness.
          A live source's caveat is a note about how to read it — OSM's attribution terms, or
          the fact that an unverified report cannot close a road — and colouring that as a
          warning on a card marked "Live" contradicts the badge next to it. */}
      {source.caveat && (
        <p
          className={`text-xs mt-3 rounded-lg px-3 py-2 border ${
            warns
              ? "border-[#fab219]/30 text-[#e0b878]"
              : "border-white/10 text-ink-secondary"
          }`}
          style={{ backgroundColor: warns ? "rgba(250,178,25,0.06)" : "var(--surface-sunken)" }}
        >
          {source.caveat}
        </p>
      )}

      <button
        className="btn-ghost !py-1.5 !min-h-[2rem] !text-xs mt-3"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
      >
        {open ? "Hide detail" : "What it feeds, and what would replace it"}
      </button>

      {open && (
        <div className="mt-3 space-y-3">
          {source.id === "incident_reports" && <LiveStats stats={source.live_stats} />}

          <div>
            <p className="label-micro mb-1.5">Feeds</p>
            <ul className="space-y-1">
              {(source.feeds || []).map((feed) => (
                <li key={feed} className="text-xs text-ink-secondary">· {feed}</li>
              ))}
            </ul>
          </div>

          <div>
            <p className="label-micro mb-1.5">Stored / refreshed</p>
            <FileMeta storage={source.storage} />
            <p className="text-xs text-ink-muted mt-1">{source.refresh}</p>
            <FeedStatus weather={source.storage?.weather} />
          </div>

          {source.human_review && (
            <div>
              <p className="label-micro mb-1.5">Human review</p>
              <p className="text-xs text-ink-secondary">{source.human_review}</p>
            </div>
          )}

          {source.upstream ? (
            <div className="rounded-lg border border-accent/25 p-3" style={{ backgroundColor: "rgba(255,255,255,0.02)" }}>
              <p className="label-micro mb-1.5">In a real deployment</p>
              <p className="text-xs text-ink">{source.upstream.name}</p>
              <p className="text-xs text-ink-secondary mt-1">{source.upstream.what}</p>
              <p className="text-[11px] text-ink-muted mt-1.5">{source.upstream.how}</p>
            </div>
          ) : (
            <p className="text-[11px] text-ink-muted">
              Already the real thing — there is no upstream feed to swap in.
            </p>
          )}

          {source.detail_endpoint && (
            <p className="text-[11px] text-ink-muted">
              Full detail: <code className="text-ink-secondary">{source.detail_endpoint}</code>
            </p>
          )}
        </div>
      )}
    </Card>
  );
};

const DataSources = () => {
  const query = useApi(() => api.getDataSources());
  const [filter, setFilter] = useState("all");

  const sources = useMemo(() => {
    const list = query.data?.sources || [];
    return [...list].sort(
      (a, b) => TRUST_ORDER.indexOf(a.trust) - TRUST_ORDER.indexOf(b.trust)
    );
  }, [query.data]);

  const visible = useMemo(
    () => (filter === "all" ? sources : sources.filter((s) => s.trust === filter)),
    [sources, filter]
  );

  const counts = query.data?.counts || {};

  if (query.error) {
    return (
      <div className="max-w-5xl mx-auto px-4 py-8">
        <ErrorState message={query.error} onRetry={query.refetch} />
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold text-ink">Where this data comes from</h1>
        <p className="text-sm text-ink-secondary mt-2 max-w-3xl leading-relaxed">
          Every figure on this platform has an origin, and those origins are not equal. This
          page names each one. It is served by the backend module that loads the data, so what
          you read here is what the code actually does — not a description of it.
        </p>
        {query.data?.headline && (
          <p
            className="text-sm mt-4 rounded-lg px-4 py-3 border border-[#fab219]/30 text-[#e0b878]"
            style={{ backgroundColor: "rgba(250,178,25,0.07)" }}
          >
            {query.data.headline}
          </p>
        )}
      </header>

      <Card className="!p-4 mb-6">
        <SectionHeading hint="What the labels mean">How far each input can be trusted</SectionHeading>
        <div className="grid gap-3 sm:grid-cols-2 mt-3">
          {TRUST_ORDER.map((trust) => (
            <div key={trust} className="flex items-start gap-2.5">
              <Badge tone={TRUST_META[trust].tone}>{TRUST_META[trust].label}</Badge>
              <div className="min-w-0">
                <p className="text-xs text-ink-secondary leading-snug">{TRUST_META[trust].line}</p>
                <p className="text-[11px] text-ink-muted mt-0.5">
                  {counts[trust] || 0} input{(counts[trust] || 0) === 1 ? "" : "s"}
                </p>
              </div>
            </div>
          ))}
        </div>
      </Card>

      <div className="mb-4">
        <Toggle
          ariaLabel="Filter data sources by trust level"
          value={filter}
          onChange={setFilter}
          options={[
            { value: "all", label: `All ${sources.length ? `(${sources.length})` : ""}`.trim() },
            ...TRUST_ORDER.filter((t) => counts[t]).map((t) => ({
              value: t,
              label: `${TRUST_META[t].label} (${counts[t]})`,
            })),
          ]}
        />
      </div>

      {query.loading ? (
        <div className="space-y-3">
          {[0, 1, 2].map((i) => (
            <Skeleton key={i} className="h-32 w-full rounded-xl" />
          ))}
        </div>
      ) : visible.length === 0 ? (
        <EmptyState title="Nothing in this category" description="Choose another trust level." />
      ) : (
        <div className="space-y-3">
          {visible.map((source) => (
            <SourceCard key={source.id} source={source} />
          ))}
        </div>
      )}

      <p className="text-xs text-ink-muted mt-8 leading-relaxed">
        The one genuinely live input is the reports people file — from this console or from
        the NER Field Reporter app on a phone at the obstruction. Both write to the same
        database, so an app report appears in the{" "}
        <Link to="/incidents" className="text-accent">review queue</Link> here.{" "}
        <Link to="/report-incident" className="text-accent">File one</Link> and watch it arrive.
      </p>
    </div>
  );
};

export default DataSources;
