# src/data_processing/data_sources.py
"""
Data provenance manifest — the single answer to "where does this number come from?".

Every figure the platform shows an operator has an origin, and those origins are not equal.
A corridor's accessibility score is arithmetic over values that were typed into a CSV by
hand; an incident count is real people reporting real obstructions; a rainfall figure is a
frozen snapshot that looks exactly like a live IMD forecast on screen and is not one. Left
undocumented, all three render as the same confident number in the same font, and the person
deciding whether to send a convoy cannot tell them apart.

This module is the one place that distinction is written down, in a form the API serves and
the web console renders, so the provenance shown to an operator cannot drift away from the
provenance in the code.

Each entry declares:

    trust       live      real data, arriving now, from the people or services named
                sample    real-world shape, illustrative values — a stand-in for a feed
                synthetic generated by us; carries no real-world information
                derived   computed from other entries here, no independent origin

    origin      who or what produced it
    upstream    what would replace it in a real deployment (IMD, GSI, CWC, ASDMA, PWD)
    feeds       which parts of the product consume it

`trust` is deliberately the first field of every entry: it is the only one that changes what
an operator should do with the number.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

logger = logging.getLogger("data_sources")

DATA_DIR = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data", "raw", "ner")
)

TRUST_LEVELS = ["live", "sample", "synthetic", "derived"]


def _file_meta(filename: str) -> dict:
    """Path (repo-relative) and last-modified time for a shipped data file."""
    path = os.path.join(DATA_DIR, filename)
    meta = {"file": f"routeOptimiserBackend/data/raw/ner/{filename}", "present": os.path.exists(path)}
    if meta["present"]:
        meta["last_modified"] = datetime.fromtimestamp(
            os.path.getmtime(path), tz=timezone.utc
        ).isoformat()
    return meta


def _incident_stats() -> dict:
    """Live counts from the incidents table, so the manifest reports the real database.

    Failure here is not fatal: the rest of the manifest is static and stays useful when the
    database is unreachable, which is exactly when someone is most likely to be reading it.
    """
    stats = {"total": None, "by_source": {}, "latest_reported_at": None, "database": None}
    try:
        from src.db.models import Incident
        from src.db.session import get_database_url, get_session

        stats["database"] = get_database_url().split("://")[0]
        session = get_session()
        try:
            rows = session.query(Incident.source, Incident.reported_at).all()
            stats["total"] = len(rows)
            for source, _ in rows:
                key = source or "unknown"
                stats["by_source"][key] = stats["by_source"].get(key, 0) + 1
            timestamps = [reported_at for _, reported_at in rows if reported_at]
            if timestamps:
                # Through the same serialiser the API uses: SQLite returns these naive, and a
                # naive ISO string reads as local time in a browser.
                from src.db.models import _iso

                stats["latest_reported_at"] = _iso(max(timestamps))
        finally:
            session.close()
    except Exception as e:  # pragma: no cover - depends on deployment environment
        logger.warning(f"Could not read incident provenance stats: {e}")
    return stats


def _rainfall_state() -> dict:
    """What the rainfall numbers actually are right now, and where they came from.

    This has to be read from the running provider rather than declared, because rainfall is
    the one input that changes trust level at runtime: live when Open-Meteo answers, the
    shipped snapshot when it does not. A manifest that hard-coded either answer would be
    wrong half the time, and wrong in the direction that flatters the platform.
    """
    state = dict(_file_meta("ner_segment_features.csv"))
    try:
        from src.data_processing.weather_provider import weather_provider
        from src.services.accessibility_service import default_provider

        features = default_provider().get_segment_features()
        observed = [f["rainfall_mm_24h"] for f in features.values() if "rainfall_mm_24h" in f]
        forecast = [
            f["forecast_rainfall_mm_48h"] for f in features.values()
            if "forecast_rainfall_mm_48h" in f
        ]
        if observed:
            state["rainfall_mm_24h_range"] = [min(observed), max(observed)]
        if forecast:
            state["forecast_rainfall_mm_48h_range"] = [min(forecast), max(forecast)]
        state["segments_covered"] = len(features)
        state["weather"] = weather_provider.status()
    except Exception as e:  # pragma: no cover
        logger.warning(f"Could not read rainfall state: {e}")
    return state


def _rainfall_source() -> dict:
    """The rainfall entry, described as whatever it currently is.

    Live and sample are genuinely different claims and get genuinely different text. What
    does not change between them is the thing most worth being careful about: IMD is named
    only as the classification whose bands the risk ladder uses, and as the upstream that a
    real deployment would source rainfall from. Open-Meteo serves national weather services'
    model output and is real live data; it is not the India Meteorological Department, and
    calling it that would be the single easiest lie to tell on this screen.
    """
    state = _rainfall_state()
    weather = state.get("weather") or {}
    live = weather.get("state") == "live"

    if live:
        summary = (
            "Live precipitation, refreshed on a timer. Real observations and forecast — "
            "from Open-Meteo, NOT from IMD."
        )
        origin = (
            "Open-Meteo, read at each corridor's midpoint: rainfall_mm_24h is summed hourly "
            "precipitation over the last 24 h, forecast_rainfall_mm_48h over the next 48 h. "
            "Open-Meteo serves the national weather services' own models (DWD ICON, ECMWF, "
            "NOAA GFS)."
        )
        refresh = (
            f"Every {weather.get('cache_ttl_seconds', 900) // 60} minutes; "
            f"last fetched {weather.get('age_seconds', 0):.0f} s ago."
        )
        caveat = (
            "Real meteorological data, and not an official Indian government feed. It is "
            "model output served by Open-Meteo, not an IMD product, and must not be "
            "described as one. The risk bands it feeds are IMD's published rainfall "
            "classification, which is a different thing from IMD's data."
        )
    else:
        summary = (
            "A frozen snapshot shipped with the repository — the live feed is not answering. "
            "It is NOT an IMD feed, and nothing refreshes it."
        )
        origin = (
            "Hand-authored values in ner_segment_features.csv, chosen to be directionally "
            "plausible for each corridor (hill corridors wetter than the Brahmaputra valley). "
            "Used whenever live rainfall is unavailable, so the platform degrades rather than "
            "fails."
        )
        refresh = "Never — the file changes only when the repository does."
        caveat = (
            "Presented in the UI as a model input, never as a forecast issued by IMD."
            + (f" Live fetch last failed with: {weather['error']}" if weather.get("error") else "")
        )

    return {
        "id": "rainfall",
        "name": "Rainfall — observed 24h and 48h forecast",
        "trust": "live" if live else "sample",
        "summary": summary,
        "origin": origin,
        "storage": state,
        "refresh": refresh,
        "feeds": [
            "rainfall_mm_24h and forecast_rainfall_mm_48h — the disaster model's two "
            "strongest features",
            "weather_risk — a quarter of every accessibility score, via a deterministic "
            "ladder over IMD's published rainfall bands",
            "corridor colouring on the map, and therefore route selection",
        ],
        "upstream": {
            "name": "India Meteorological Department (IMD)",
            "what": "Observed rainfall and district-level quantitative precipitation forecast",
            "how": (
                "Implement get_segment_features() on a provider that polls the IMD feed and "
                "swap it in — exactly as LiveWeatherNERDataProvider does for Open-Meteo. "
                "Nothing below the provider interface changes."
            ),
        },
        "caveat": caveat,
    }


def get_data_sources() -> dict:
    """The full manifest, with live figures filled in where they exist."""
    incidents = _incident_stats()

    sources = [
        {
            "id": "incident_reports",
            "name": "Community incident reports",
            "trust": "live",
            "summary": (
                "Real reports of real obstructions, filed by whoever is standing at one — "
                "the only genuinely live input this platform has."
            ),
            "origin": (
                "Citizens and field officers, through the NER Field Reporter app (Expo) and "
                "the Report an incident form on the web console. Both write to the same "
                "table through the same endpoint; an account is not required to report."
            ),
            "storage": (
                "incidents table — SQLite locally, PostgreSQL when DATABASE_URL is set. "
                "One database serves both clients, which is why an app report appears in the "
                "web review queue."
            ),
            "refresh": "On submission, and on offline-queue sync when the phone regains signal.",
            "human_review": (
                "Deterministic, never ML: a verifier confirms or rejects each report, and a "
                "severity-5 blocking closure needs a second verifier to countersign."
            ),
            "feeds": [
                "Incident risk component of the accessibility score",
                "Corridor closure when a severe blocking report is verified",
                "Review queue on the web console",
                "Recent incidents on the dashboard and map",
            ],
            "live_stats": incidents,
            "upstream": None,
            "caveat": (
                "Unverified reports raise a corridor's risk but never close it on their own."
            ),
        },
        _rainfall_source(),
        {
            "id": "terrain",
            "name": "Terrain — slope and elevation",
            "trust": "sample",
            "summary": "Rough physical approximations per corridor, not sampled from a DEM.",
            "origin": "ner_segment_features.csv (slope_gradient_deg, elevation_m).",
            "storage": _file_meta("ner_segment_features.csv"),
            "refresh": "Static.",
            "feeds": ["Slope and elevation features of the disaster prediction model"],
            "upstream": {
                "name": "SRTM / Cartosat DEM",
                "what": "Per-segment slope and elevation sampled along the corridor geometry",
                "how": "Sample the DEM along each segment polyline at ingest time.",
            },
            "caveat": None,
        },
        {
            "id": "historical_events",
            "name": "Historical landslide and flood counts (5 years)",
            "trust": "synthetic",
            "summary": (
                "Invented counts. They carry no information about what has actually happened "
                "on these roads."
            ),
            "origin": "historical_landslides_5y / historical_floods_5y in ner_segment_features.csv.",
            "storage": _file_meta("ner_segment_features.csv"),
            "refresh": "Static.",
            "feeds": ["History features of the disaster prediction model"],
            "upstream": {
                "name": "GSI landslide inventory · CWC and ASDMA flood records · NDMA",
                "what": "Recorded events per corridor with dates and severity",
                "how": "Spatial join of official event records to corridor geometry.",
            },
            "caveat": (
                "Not sourced from GSI, NDMA, ASDMA or any official disaster record, and must "
                "never be described as such."
            ),
        },
        {
            "id": "road_segments",
            "name": "Road corridors and their baseline risk",
            "trust": "sample",
            "summary": (
                "Real corridors (NH27, NH10, NH29 and the rest) with approximate distances; "
                "the risk numbers attached to them are placeholders."
            ),
            "origin": (
                "ner_road_segments.csv. Corridor names and approximate road distances are "
                "public knowledge; road_status, weather_risk, landslide_risk, flood_risk, "
                "incident_risk and delay_factor are synthetic placeholders chosen to be "
                "illustrative of corridors that are widely reported as problematic."
            ),
            "storage": _file_meta("ner_road_segments.csv"),
            "refresh": "Static.",
            "feeds": [
                "Every accessibility score",
                "The routing graph",
                "Corridor risk shown on the map",
            ],
            "upstream": {
                "name": "State PWD and NHAI road condition feeds · BRO closure notices",
                "what": "Live road status, closures and restriction notices",
                "how": "Poll the PWD/BRO status feed and map each notice to a corridor id.",
            },
            "caveat": "The risk values are the largest single assumption in the platform.",
        },
        {
            "id": "locations",
            "name": "Locations — towns and district headquarters",
            "trust": "sample",
            "summary": (
                "Real towns at real coordinates across the eight NER states plus the Siliguri "
                "gateway; the district field is an approximation."
            ),
            "origin": "ner_locations.csv.",
            "storage": _file_meta("ner_locations.csv"),
            "refresh": "Static.",
            "feeds": ["Corridor endpoints", "Route planner origin and destination lists"],
            "upstream": {
                "name": "Survey of India / LGD district master",
                "what": "Authoritative place and district codes",
                "how": "Key locations by LGD code instead of by name.",
            },
            "caveat": None,
        },
        {
            "id": "disaster_model",
            "name": "Disaster prediction model",
            "trust": "synthetic",
            "summary": (
                "A real, explainable ML pipeline trained on data we generated from written "
                "rules. It has learned our rules, not the region's weather."
            ),
            "origin": (
                "Random Forest, trained at build time on seeded synthetic samples produced by "
                "generate_training_data() in src/modeling/disaster_prediction.py."
            ),
            "storage": "Persisted forests alongside the source; retrained deterministically from the seed.",
            "refresh": "On deploy.",
            "feeds": ["Flood and landslide disruption probability, with per-prediction drivers"],
            "upstream": {
                "name": "Historical event records + IMD rainfall archives",
                "what": "Labelled disruption events to train against",
                "how": "Retrain the same pipeline on real labels; the interface does not change.",
            },
            "caveat": (
                "The only ML in the platform. It predicts future disruption probability and "
                "nothing else — it does not score accessibility, choose routes, or verify "
                "reports. Its probabilities are not validated forecasts."
            ),
            "detail_endpoint": "/api/ner/model-info",
        },
        {
            "id": "accessibility_score",
            "name": "Accessibility score (0-100)",
            "trust": "derived",
            "summary": (
                "Arithmetic, not a model: a fixed weighted sum of the risk inputs above, so "
                "any score can be recomputed by hand."
            ),
            "origin": (
                "100 - (0.25·weather + 0.30·landslide + 0.20·flood + 0.15·incident + "
                "0.10·delay), per the SIH Module 1 formula. Deterministic and ML-free by policy."
            ),
            "storage": "Computed per request from road_segments and live incident reports.",
            "refresh": "Recomputed whenever a report changes conditions; cached for seconds.",
            "feeds": ["Corridor colouring on the map", "Dashboard network average", "Route ranking"],
            "upstream": None,
            "caveat": (
                "Inherits the trust of its inputs: mostly sample risk values, plus live "
                "incident reports."
            ),
        },
        {
            "id": "route_optimisation",
            "name": "Optimised routes",
            "trust": "derived",
            "summary": (
                "Multi-objective A* with Pareto pruning over the corridor graph — a search, "
                "not a prediction."
            ),
            "origin": (
                "src/optimization/ner_router.py over the graph built from road_segments, with "
                "edge costs from distance, the accessibility score and the cargo/transport "
                "profile. Verified severe blocking incidents remove a corridor from the graph."
            ),
            "storage": "Computed per request; a planned shipment stores a snapshot of the route it was given.",
            "refresh": "Per request.",
            "feeds": ["Shipment planner", "Alternative route suggestions", "Transport mode ranking"],
            "upstream": {
                "name": "Real road network geometry (OSM / NHAI)",
                "what": "True routable geometry rather than a 28-node corridor graph",
                "how": "Replace the graph builder's input; the search is unchanged.",
            },
            "caveat": "Travel times are estimated from distance and a hill/plains speed assumption.",
        },
        {
            "id": "places",
            "name": "Place search and nearby facilities",
            "trust": "live",
            "summary": "Real OpenStreetMap data, fetched at query time, with no API key.",
            "origin": (
                "Photon for geocoding and Overpass for nearby facilities, queried behind the "
                "28 local corridor nodes, which always answer first and never wait on the network."
            ),
            "storage": "Cached in memory for minutes; nothing is persisted.",
            "refresh": "Per query, time-boxed, failure-tolerant.",
            "feeds": ["Free-text origin and destination search", "Nearby facilities and their listed phone numbers"],
            "upstream": None,
            "caveat": (
                "ODbL-licensed; attribution is carried in every response. Contact details are "
                "passed through verbatim from OSM and never synthesised."
            ),
        },
    ]

    counts = {}
    for source in sources:
        counts[source["trust"]] = counts.get(source["trust"], 0) + 1

    rainfall_live = any(s["id"] == "rainfall" and s["trust"] == "live" for s in sources)
    rainfall_line = (
        "Rainfall is live from Open-Meteo (real model output, not an IMD product). "
        if rainfall_live
        else "Rainfall is a frozen snapshot — the live feed is not answering. "
    )

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "trust_levels": {
            "live": "Real data arriving now from the people or services named.",
            "sample": "Real-world shape, illustrative values — a stand-in for a feed that is not wired in.",
            "synthetic": "Generated by us. Carries no real-world information.",
            "derived": "Computed from the entries above; inherits their trust.",
        },
        "counts": counts,
        "headline": (
            "Incident reports and OpenStreetMap place data are live. "
            + rainfall_line
            + "Terrain, corridor landslide/flood risk and the model's training data are "
            "sample or synthetic — and nothing here is an official IMD, GSI, CWC or ASDMA "
            "feed."
        ),
        "sources": sources,
    }
